version: '3.8'

services:
  db:
    image: postgres:15
    container_name: database_postgres
    env_file:
      - variaveis.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  airflow:
    image: apache/airflow:2.8.1
    container_name: airflow
    env_file:
      - variaveis.env
    depends_on:
      - db
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    ports:
      - "8080:8080"
    command: >
      bash -c "airflow db upgrade &&
               airflow users create --username admin --password admin --firstname Admin --lastname User --role Admin --email admin@example.com &&
               airflow webserver"

  airflow-scheduler:
    image: apache/airflow:2.8.1
    container_name: airflow_scheduler
    env_file:
      - variaveis.env
    depends_on:
      - db
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    command: >
      bash -c "airflow db upgrade &&
               airflow scheduler"

  dbt:
    image: ghcr.io/dbt-labs/dbt-postgres:1.7.9
    container_name: dbt
    depends_on:
      - db
    environment:
      DBT_PROFILES_DIR: /dbt
      DBT_DOCS_SERVER_HOST: 0.0.0.0
    volumes:
      - ./dbt:/dbt
    working_dir: /dbt
    entrypoint: ["tail", "-f", "/dev/null"]
    ports:
      - "8081:8080"

volumes:
  postgres_data: